# -*- coding: utf-8 -*-
"""coletando_twitters.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gxtGjX2r4I1Fx1LD_4QsnXCzzM_AV66u

https://apps.twitter.com/
"""

# !pip install tweepy
import tweepy
import json

with open('credenciais.json') as arquivo:
  credenciais = json.load(arquivo)

print(credenciais['consumer_key'])

# Criando o objeto para autenticação
auth = tweepy.OAuthHandler(credenciais['consumer_key'], credenciais['consumer_secret'])
# Adicionando as credenciais de acesso
auth.set_access_token(credenciais['access_token'], credenciais['access_token_secret'])
# Cria o objeto para acesso a API a partir da autenticação
api = tweepy.API(auth)

# coletando os twitters em minha timeline
tweets_da_minha_timeline = api.home_timeline()
# Mostrando os twitters
for tweet in tweets_da_minha_timeline:
   # realizando o print dos twitters que estão armazenados dentro do objeto twitter
   print(tweet.text)

type(tweets_da_minha_timeline[0])

#coletando twitters através da #
# Criando o objeto twitter
api = tweepy.API(auth)

# O termo que desejamos pesquisar
pesquisa = "Bolsonaro"
# linguagem (padrão ISO 639-1 )
linguagem = "pt"

# definindo a pesquisa a ser realizada
resultados = api.search(q=pesquisa, lang=linguagem)

# realiza o print para cada twitter encontrado
for tweet in resultados:
   # realiza o print do texto presente no json retornado pelo twitter
   print(tweet.user.screen_name,"Tweetado:",tweet.text)

#trending topics
# Where On Earth ID para o Brazil é 23424768.
BRAZIL_WOE_ID = 23424768
 
brazil_trends = api.trends_place(BRAZIL_WOE_ID)
 
trends = json.loads(json.dumps(brazil_trends, indent=1))
 
for trend in trends[0]["trends"]:
	print (trend["name"])#.strip("#"))